baseURL: "bemiles.github.io/" 
title: Dr. Brittany E. Miles
paginate: 20
theme: PaperMod


enableInlineShortcodes: false
enableRobotsTXT: True

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: CV
          url: CV_BEM.pdf
          weight: 4

params:
    description: "I am an astronomy postdoc at the University of Arizona.
consequat."
    author: Brittany E. Miles
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Brittany E. Miles
          subtitle: "I am an <b>assistant professor</b> at Steward Observatory within the University of Arizona. I use mid-infrared spectroscopy to characterize the atmospheres of brown dwarfs and exoplanets. I want to improve ground-based mid-infrared instruments to characterize existing exoplanets and find Earth-like planets."
          imageUrl: "bd.png"
          imageWidth: 700
          imageHeight: 465
          imageTitle: Brittany
          buttons:
            - name: About
              url: about
            - name: Projects
              url: projects
            - name: Research Group
              url: group
            - name: Research Opportunities
              url: opportunities
            - name: CV
              url: CV_BEM.pdf
            - name: Publications
              url: "https://ui.adsabs.harvard.edu/search/q=docs(library%2FEN60j0GSQr2qKjHKjcZCEg)&sort=date%20desc%2C%20bibcode%20desc&p_=0"
            - name: Blog
              url: "https://infraredastronomy.tumblr.com/"
    socialIcons:
        - name: CV
          url: CV_BEM.pdf
        - name: Email
          url: mailto:bemiles@arizona.edu
        
        

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        image: "bd.png"
        hidden: false
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Brittany E. Miles"
      icon: "sunflower.ico"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
