baseURL: "bemiles.github.io/" 
title: Dr. Brittany E. Miles
paginate: 20
theme: PaperMod

enableInlineShortcodes: false
enableRobotsTXT: false

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: CV
          url: CV_BEM_08172025.pdf
          weight: 4

params:
    description: "I am an astronomy postdoc at the University of Arizona.
consequat."
    author: Brittany E. Miles
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Brittany E. Miles
          subtitle: "I use mid-infrared spectroscopy to characterize the atmospheres of brown dwarfs and exoplanets. I want to improve ground-based mid-infrared instruments to characterize existing exoplanets and find Earth-like planets. I am currently a 51 Pegasi b and Presidential Postdoctoral Fellow at the University of Arizona. Fall 2025 I will join the faculty at Steward Observatory as an assistant professor."
          imageUrl: "headshot2.JPG"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Brittany
          buttons:
            - name: About
              url: about
            - name: Projects
              url: projects
            - name: Research Group
              url: group
            - name: Research Opportunities
              url: opportunities
            - name: CV
              url: CV_BEM_08172025.pdf
            - name: Blog
              url: "https://infraredastronomy.tumblr.com/"
    socialIcons:
        - name: CV
          url: CV_BEM_08172025.pdf
        - name: Email
          url: mailto:bemiles@arizona.edu
        
        

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Brittany E. Miles"
      icon: "sunflower.ico"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
